services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.lab.kanare.dev
    dns:
      - 192.168.11.11
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks: {}
