global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets:
          - "192.168.11.11:9100"   # vm-infra
          - "192.168.11.13:9100"   # vm-monitoring
          - "192.168.11.20:9100"   # vm-apps
          - "192.168.11.21:9100"   # vm-dev
        labels:
          env: "homelab"

  - job_name: "esp32"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "192.168.11.100:80"    # 01-esp32
        labels:
          env: "homelab"
          device: "esp32"
