global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["192.168.11.10:9100"]   # proxmox
        labels:
          env: "homelab"
          host: "pve"
          role: "proxmox"
      - targets: ["192.168.11.11:9100"]   # vm-infra
        labels:
          env: "homelab"
          host: "vm-infra"
          role: "infra"
      - targets: ["192.168.11.13:9100"]   # vm-monitoring
        labels:
          env: "homelab"
          host: "vm-monitoring"
          role: "monitoring"
      - targets: ["192.168.11.20:9100"]   # vm-apps
        labels:
          env: "homelab"
          host: "vm-apps"
          role: "apps"
      - targets: ["192.168.11.21:9100"]   # vm-dev
        labels:
          env: "homelab"
          host: "vm-dev"
          role: "dev"
    relabel_configs:
      - source_labels: ["host"]
        target_label: instance

  - job_name: "esp32"
    scrape_interval: 30s
    static_configs:
      - targets: ["192.168.11.100:80"]    # 01-esp32
        labels:
          env: "homelab"
          host: "esp32-01"
          role: "iot"
          device: "esp32-01"
    relabel_configs:
      - source_labels: ["device"]
        target_label: instance
