all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.11.10
    infra:
      hosts:
        vm-infra:
          ansible_host: 192.168.11.11
    monitoring:
      hosts:
        vm-monitoring:
          ansible_host: 192.168.11.13
    apps:
      hosts:
        vm-apps:
          ansible_host: 192.168.11.20
    dev:
      hosts:
        vm-dev:
          ansible_host: 192.168.11.21
