all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.11.10
    monitoring:
      hosts:
        vm-apps:
          ansible_host: 192.168.11.20
    apps:
      hosts:
        vm-apps:
          ansible_host: 192.168.11.20
