- Infrastructure:
    - Proxmox VE:
        href: https://pve.lab.kanare.dev
        description: Hypervisor
        icon: proxmox.png
        siteMonitor: https://pve.lab.kanare.dev
        widget:
          type: proxmox
          url: https://192.168.11.10:8006
          username: homepage@pve!homepage-token
          password: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
          node: pve

- Monitoring:
    - Grafana:
        href: https://grafana.lab.kanare.dev
        description: Metrics Dashboards
        icon: grafana.png
        siteMonitor: https://grafana.lab.kanare.dev
    - Prometheus:
        href: https://prometheus.lab.kanare.dev
        description: Metrics Scraper
        icon: prometheus.png
        siteMonitor: https://prometheus.lab.kanare.dev
