---
- name: restart code-server
  ansible.builtin.systemd:
    name: "code-server@{{ ansible_user }}"
    state: restarted

- name: restart cloudcli
  ansible.builtin.systemd:
    name: cloudcli
    state: restarted
    daemon_reload: true
